# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b051aa1c4efa75c956b8bb2edfff6c556c87ba67ce31fbc57c197fc3f0361aa11397c365754dd06bd1ed02dfecd360e6b9f4879265251db89c02ca5466ab118

test:
  secret_key_base: 8b8ba542b1e5eca63f4ad76a703c5a7e0c023e94fd2b4def2db3fd9a17b1091db88190128d0ab27ab7875d102373f69378d8df2258e3b830a383f620eb492284

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
